version: '3'
services:
  db:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-db
    container_name: interview-db
    volumes:
      - ./db/database.sql:/db/database.sql
      - ./db/data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
